[package]
name = "forge"
edition = "2021"
version.workspace = true

[dependencies]
# TODO: Don't use the workspace, instead explicitly
# depend on the version with the git dependency
stahl-core = { path = "../stahl-core", version = "0.6.0", features = ["dylibs", "stacker", "sync", "git"] }

[build-dependencies]
stahl-core = { path = "../stahl-core", version = "0.6.0", features = ["dylibs", "stacker", "sync", "git"] }

[features]
default = ["dylib-build"]
dylib-build = ["stahl-core/dylib-build"]
