[package]
name = "stahl-webserver"
version = "0.1.0"
edition = "2021"

[lib]
name = "stahl_webserver"
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stahl-core = { workspace = true }
axum = { version = "0.6.2", features = ["query"] }
tokio = { version = "1.0", features = ["full"] }
crossbeam = "0.8.2"
serde_json = "1.0.92"
abi_stable = "0.11.1"
